name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - 
        name: 'deploy'
        id: deploy
        run: |
          npm run deploy
      